name: Run Terraform on Azure

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Set up Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.10.3  

    # Authenticating 
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Initialize Terraform
    - name: Terraform Init
      run: terraform init
      working-directory: ./terraform_files
      
    # Terraform Plan
    - name: Terraform Plan
      run: terraform plan -out=tfplan
      working-directory: ./terraform_files
      env:
        TF_VAR_keydata: ${{ secrets.TF_VAR_KEYDATA }}
        TF_VAR_adm_user: ${{ secrets.TF_VAR_ADM_USER }}
        TF_VAR_environment_name: ${{ secrets.TF_VAR_ENVIRON_NAME }}
        TF_VAR_rg_name: ${{ secrets.TF_VAR_RESOURCE_GROUP_NAME }}
    
    # Terraform Apply
    - name: Terraform Apply
      run: terraform apply -auto-approve tfplan
      working-directory: ./terraform_files
      env:
        TF_VAR_keydata: ${{ secrets.TF_VAR_KEYDATA }}
        TF_VAR_adm_user: ${{ secrets.TF_VAR_ADM_USER }}
        TF_VAR_environment_name: ${{ secrets.TF_VAR_ENVIRON_NAME }}
        TF_VAR_rg_name: ${{ secrets.TF_VAR_RESOURCE_GROUP_NAME }}